/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"

/* Header for class org_swdc_clang_libtooling_ClangLibTools */

#ifndef _Included_org_swdc_clang_libtooling_ClangLibTools
#define _Included_org_swdc_clang_libtooling_ClangLibTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_clang_libtooling_ClangLibTools
 * Method:    parseHeaderFiles
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_clang_libtooling_ClangLibTools_parseHeaderFiles
  (JNIEnv *, jclass, jstring, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
