/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni/jni.h"
#include <ffi.h>
/* Header for class org_swdc_layered_ExternalInvoker */

#ifndef _Included_org_swdc_layered_ExternalInvoker
#define _Included_org_swdc_layered_ExternalInvoker
#ifdef __cplusplus
extern "C" {
#endif 

	const int LAYER_ADDRESS = 0;
	
	const int LAYER_INT = 1;

	const int LAYER_UINT = 2;

	const int LAYER_LONG = 3;

	const int LAYER_ULONG = 4;

	const int LAYER_FLOAT = 5;

	const int LAYER_DOUBLE = 6;

	const int LAYER_CHAR = 7;

	const int LAYER_UCHAR = 8;

	const int LAYER_BOOL = 9;

	const int LAYER_VOID = 10;

	typedef struct CallHandler {
		ffi_type** types;
		ffi_cif* cif;
	} LayerCall;

	typedef struct CallbackHandler {
		void* closure;
		void* callingAddr;
		void* javaCb;
	} LayerCallBack;
/*
 * Class:     org_swdc_layered_ExternalInvoker
 * Method:    loadLibrary
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_layered_ExternalInvoker_loadLibrary
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_swdc_layered_ExternalInvoker
 * Method:    unloadLibrary
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_ExternalInvoker_unloadLibrary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_swdc_layered_ExternalInvoker
 * Method:    getLibrarySymbols
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_swdc_layered_ExternalInvoker_getLibrarySymbols
(JNIEnv*, jclass, jlong);

/*
 * Class:     org_swdc_layered_ExternalInvoker
 * Method:    lookup
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_layered_ExternalInvoker_lookup
  (JNIEnv *, jclass, jlong, jstring);


/*
 * Class:     org_swdc_layered_ExternalInvoker
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_layered_ExternalInvoker_getLastError
  (JNIEnv *, jclass);

/*
 * Class:     org_swdc_layered_ExternalInvoker
 * Method:    createFFICIF
 * Signature: ([II)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_layered_ExternalInvoker_createFFICIF
(JNIEnv*, jclass, jintArray, jint);

/*
 * Class:     org_swdc_layered_ExternalInvoker
 * Method:    destroyFFICIF
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_ExternalInvoker_destroyFFICIF
(JNIEnv*, jclass, jlong);


/*
 * Class:     org_swdc_layered_ExternalInvoker
 * Method:    call
 * Signature: (JJJJ[I)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_ExternalInvoker_call
(JNIEnv*, jclass, jlong, jlong, jlong, jlong, jintArray);


/*
 * Class:     org_swdc_layered_ExternalInvoker
 * Method:    createClosure
 * Signature: (Ljava/lang/Object;J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_layered_ExternalInvoker_createClosure
(JNIEnv*, jclass, jobject, jlong);

/*
 * Class:     org_swdc_layered_ExternalInvoker
 * Method:    getClosureFunctionAddr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_layered_ExternalInvoker_getClosureFunctionAddr
(JNIEnv*, jclass, jlong);

/*
 * Class:     org_swdc_layered_ExternalInvoker
 * Method:    freeClosure
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_ExternalInvoker_freeClosure
(JNIEnv*, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
