/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni/jni.h"
/* Header for class org_swdc_layered_MemoryManager */

#ifndef _Included_org_swdc_layered_MemoryManager
#define _Included_org_swdc_layered_MemoryManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    sizeOfPointer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_layered_MemoryManager_sizeOfPointer
  (JNIEnv *, jclass);
/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    sizeOfInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_layered_MemoryManager_sizeOfInt
  (JNIEnv *, jclass);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    sizeOfLong
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_layered_MemoryManager_sizeOfLong
  (JNIEnv *, jclass);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    sizeOfDouble
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_layered_MemoryManager_sizeOfDouble
  (JNIEnv *, jclass);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    sizeOfFloat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_layered_MemoryManager_sizeOfFloat
  (JNIEnv *, jclass);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    sizeOfByte
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_layered_MemoryManager_sizeOfByte
  (JNIEnv *, jclass);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    sizeOfShort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_layered_MemoryManager_sizeOfShort
  (JNIEnv *, jclass);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    sizeOfBoolean
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_layered_MemoryManager_sizeOfBoolean
  (JNIEnv *, jclass);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    malloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_layered_MemoryManager_malloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    mallocAligned
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_layered_MemoryManager_mallocAligned
(JNIEnv*, jclass, jint, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    free
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_layered_MemoryManager_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    freeAligned
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_layered_MemoryManager_freeAligned
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    memset
 * Signature: (JIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_layered_MemoryManager_memset
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    memcpy
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_layered_MemoryManager_memcpy
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    strlen
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_layered_MemoryManager_strlen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    directBuffer
 * Signature: (JJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_swdc_layered_MemoryManager_directBuffer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readInt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_layered_MemoryManager_readInt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readIntArray
 * Signature: (JI)[I
 */
JNIEXPORT jintArray JNICALL Java_org_swdc_layered_MemoryManager_readIntArray
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeIntArray
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeIntArray
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeInt
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeInt
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readLong
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_layered_MemoryManager_readLong
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readLongArray
 * Signature: (JI)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_swdc_layered_MemoryManager_readLongArray
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeLong
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeLong
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeLongArray
 * Signature: (J[J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeLongArray
  (JNIEnv *, jclass, jlong, jlongArray);


/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readDouble
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_layered_MemoryManager_readDouble
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readDoubleArray
 * Signature: (JI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_swdc_layered_MemoryManager_readDoubleArray
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeDouble
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeDouble
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeDoubleArray
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeDoubleArray
  (JNIEnv *, jclass, jlong, jdoubleArray);


/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readFloat
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_org_swdc_layered_MemoryManager_readFloat
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readFloatArray
 * Signature: (JI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_swdc_layered_MemoryManager_readFloatArray
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeFloat
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeFloat
  (JNIEnv *, jclass, jlong, jint, jfloat);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeFloatArray
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeFloatArray
  (JNIEnv *, jclass, jlong, jfloatArray);
/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readShort
 * Signature: (JI)S
 */
JNIEXPORT jshort JNICALL Java_org_swdc_layered_MemoryManager_readShort
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readShortArray
 * Signature: (JI)[S
 */
JNIEXPORT jshortArray JNICALL Java_org_swdc_layered_MemoryManager_readShortArray
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeShort
 * Signature: (JIS)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeShort
  (JNIEnv *, jclass, jlong, jint, jshort);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeShortArray
 * Signature: (J[S)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeShortArray
  (JNIEnv *, jclass, jlong, jshortArray);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readAddress
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_layered_MemoryManager_readAddress
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readAddressArray
 * Signature: (JI)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_swdc_layered_MemoryManager_readAddressArray
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeAddress
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeAddress
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeAddressArray
 * Signature: (J[J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeAddressArray
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readBoolean
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_layered_MemoryManager_readBoolean
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readBooleanArray
 * Signature: (JI)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_org_swdc_layered_MemoryManager_readBooleanArray
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeBoolean
 * Signature: (JIZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeBoolean
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeBooleanArray
 * Signature: (J[Z)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeBooleanArray
  (JNIEnv *, jclass, jlong, jbooleanArray);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readByte
 * Signature: (JI)B
 */
JNIEXPORT jbyte JNICALL Java_org_swdc_layered_MemoryManager_readByte
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    readByteArray
 * Signature: (JII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_swdc_layered_MemoryManager_readByteArray
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeByte
 * Signature: (JIB)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeByte
  (JNIEnv *, jclass, jlong, jint, jbyte);

/*
 * Class:     org_swdc_layered_MemoryManager
 * Method:    writeByteArray
 * Signature: (JI[BII)V
 */
JNIEXPORT void JNICALL Java_org_swdc_layered_MemoryManager_writeByteArray
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
